/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Coach struct {
	FirstName string `json:"first_name,omitempty"`
	LastName string `json:"last_name,omitempty"`
	HireDate string `json:"hire_date,omitempty"`
	Seasons []CoachSeasons `json:"seasons,omitempty"`
}
