/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RankingWeekRanks struct {
	Rank int32 `json:"rank,omitempty"`
	School string `json:"school,omitempty"`
	Conference string `json:"conference,omitempty"`
	FirstPlaceVotes int32 `json:"firstPlaceVotes,omitempty"`
	Points int32 `json:"points,omitempty"`
}
