/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PortalPlayer struct {
	Season int32 `json:"season,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	LastName string `json:"lastName,omitempty"`
	Position string `json:"position,omitempty"`
	Origin string `json:"origin,omitempty"`
	Destination string `json:"destination,omitempty"`
	TransferDate string `json:"transferDate,omitempty"`
	Rating float64 `json:"rating,omitempty"`
	Stars int32 `json:"stars,omitempty"`
	Eligibility string `json:"eligibility,omitempty"`
}
