/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PlayWp struct {
	GamesId int32 `json:"gamesId,omitempty"`
	PlayId int32 `json:"playId,omitempty"`
	PlayText string `json:"playText,omitempty"`
	HomeId int32 `json:"homeId,omitempty"`
	Home string `json:"home,omitempty"`
	AwayId int32 `json:"awayId,omitempty"`
	Away string `json:"away,omitempty"`
	Spread float64 `json:"spread,omitempty"`
	HomeBall bool `json:"homeBall,omitempty"`
	HomeScore int32 `json:"homeScore,omitempty"`
	AwayScore int32 `json:"awayScore,omitempty"`
	TimeRemaining int32 `json:"timeRemaining,omitempty"`
	YardLine int32 `json:"yardLine,omitempty"`
	Down int32 `json:"down,omitempty"`
	Distance int32 `json:"distance,omitempty"`
	HomeWinProb float64 `json:"homeWinProb,omitempty"`
	PlayNumber int32 `json:"playNumber,omitempty"`
}
