/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BoxScoreTeamsRushing struct {
	Team string `json:"team,omitempty"`
	PowerSuccess float64 `json:"powerSuccess,omitempty"`
	StuffRate float64 `json:"stuffRate,omitempty"`
	LineYards float64 `json:"lineYards,omitempty"`
	LineYardsAverage float64 `json:"lineYardsAverage,omitempty"`
	SecondLevelYards int32 `json:"secondLevelYards,omitempty"`
	SecondLevelYardsAverage float64 `json:"secondLevelYardsAverage,omitempty"`
	OpenFieldYards int32 `json:"openFieldYards,omitempty"`
	OpenFieldYardsAverage float64 `json:"openFieldYardsAverage,omitempty"`
}
