/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DraftTeam struct {
	Location string `json:"location,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Logo string `json:"logo,omitempty"`
}
