/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Venue struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Capacity int32 `json:"capacity,omitempty"`
	Grass bool `json:"grass,omitempty"`
	City string `json:"city,omitempty"`
	State string `json:"state,omitempty"`
	Zip string `json:"zip,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	Location *VenueLocation `json:"location,omitempty"`
	Elevation float64 `json:"elevation,omitempty"`
	YearConstructed int32 `json:"year_constructed,omitempty"`
	Dome bool `json:"dome,omitempty"`
	Timezone string `json:"timezone,omitempty"`
}
