/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PositionGroupRecruitingRating struct {
	Team string `json:"team,omitempty"`
	Conference string `json:"conference,omitempty"`
	PositionGroup string `json:"positionGroup,omitempty"`
	AverageRating float64 `json:"averageRating,omitempty"`
	TotalRating float64 `json:"totalRating,omitempty"`
	Commits float64 `json:"commits,omitempty"`
	AverageStars float64 `json:"averageStars,omitempty"`
}
