/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DraftPick struct {
	CollegeAthleteId int32 `json:"collegeAthleteId,omitempty"`
	NflAthleteId int32 `json:"nflAthleteId,omitempty"`
	CollegeId int32 `json:"collegeId,omitempty"`
	CollegeTeam string `json:"collegeTeam,omitempty"`
	CollegeConference string `json:"collegeConference,omitempty"`
	NflTeam string `json:"nflTeam,omitempty"`
	Year int32 `json:"year,omitempty"`
	Overall int32 `json:"overall,omitempty"`
	Round int32 `json:"round,omitempty"`
	Pick int32 `json:"pick,omitempty"`
	Name string `json:"name,omitempty"`
	Position string `json:"position,omitempty"`
	Height int32 `json:"height,omitempty"`
	Weight int32 `json:"weight,omitempty"`
	PreDraftRanking int32 `json:"preDraftRanking,omitempty"`
	PreDraftPositionRanking int32 `json:"preDraftPositionRanking,omitempty"`
	PreDraftGrade int32 `json:"preDraftGrade,omitempty"`
	HometownInfo *DraftPickHometownInfo `json:"hometownInfo,omitempty"`
}
