/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PlayStat struct {
	GameId int32 `json:"gameId,omitempty"`
	Season int32 `json:"season,omitempty"`
	Week int32 `json:"week,omitempty"`
	Team string `json:"team,omitempty"`
	Conference string `json:"conference,omitempty"`
	Opponent string `json:"opponent,omitempty"`
	TeamScore int32 `json:"teamScore,omitempty"`
	OpponentScore int32 `json:"opponentScore,omitempty"`
	DriveId int32 `json:"driveId,omitempty"`
	PlayId int32 `json:"playId,omitempty"`
	Period int32 `json:"period,omitempty"`
	Clock *DriveStartTime `json:"clock,omitempty"`
	YardsToGoal int32 `json:"yardsToGoal,omitempty"`
	Down int32 `json:"down,omitempty"`
	Distance int32 `json:"distance,omitempty"`
	AthleteId int32 `json:"athleteId,omitempty"`
	AthleteName string `json:"athleteName,omitempty"`
	StatType string `json:"statType,omitempty"`
	Stat int32 `json:"stat,omitempty"`
}
