/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Drive struct {
	Offense string `json:"offense,omitempty"`
	OffenseConference string `json:"offense_conference,omitempty"`
	Defense string `json:"defense,omitempty"`
	DefenseConference string `json:"defense_conference,omitempty"`
	GameId int32 `json:"game_id,omitempty"`
	Id int32 `json:"id,omitempty"`
	DriveNumber int32 `json:"drive_number,omitempty"`
	Scoring bool `json:"scoring,omitempty"`
	StartPeriod int32 `json:"start_period,omitempty"`
	StartYardline int32 `json:"start_yardline,omitempty"`
	StartYardsToGoal int32 `json:"start_yards_to_goal,omitempty"`
	StartTime *DriveStartTime `json:"start_time,omitempty"`
	EndPeriod int32 `json:"end_period,omitempty"`
	EndYardline int32 `json:"end_yardline,omitempty"`
	EndYardsToGoal int32 `json:"end_yards_to_goal,omitempty"`
	EndTime *DriveStartTime `json:"end_time,omitempty"`
	Plays int32 `json:"plays,omitempty"`
	Yards int32 `json:"yards,omitempty"`
	DriveResult string `json:"drive_result,omitempty"`
	IsHomeOffense bool `json:"is_home_offense,omitempty"`
	StartOffenseScore int32 `json:"start_offense_score,omitempty"`
	StartDefenseScore int32 `json:"start_defense_score,omitempty"`
	EndOffenseScore int32 `json:"end_offense_score,omitempty"`
	EndDefenseScore int32 `json:"end_defense_score,omitempty"`
}
