/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LivePlayByPlay struct {
	Id int32 `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
	Period int32 `json:"period,omitempty"`
	Clock string `json:"clock,omitempty"`
	Possession string `json:"possession,omitempty"`
	Down int32 `json:"down,omitempty"`
	Distance int32 `json:"distance,omitempty"`
	YardsToGoal int32 `json:"yardsToGoal,omitempty"`
	Teams []LivePlayByPlayTeams `json:"teams,omitempty"`
	Drives []LivePlayByPlayDrives `json:"drives,omitempty"`
}
