/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Play struct {
	Id int32 `json:"id,omitempty"`
	DriveId int32 `json:"drive_id,omitempty"`
	GameId int32 `json:"game_id,omitempty"`
	DriveNumber int32 `json:"drive_number,omitempty"`
	PlayNumber int32 `json:"play_number,omitempty"`
	Offense string `json:"offense,omitempty"`
	OffenseConference string `json:"offense_conference,omitempty"`
	OffenseScore int32 `json:"offense_score,omitempty"`
	Defense string `json:"defense,omitempty"`
	Home string `json:"home,omitempty"`
	Away string `json:"away,omitempty"`
	DefenseConference string `json:"defense_conference,omitempty"`
	DefenseScore int32 `json:"defense_score,omitempty"`
	Period int32 `json:"period,omitempty"`
	Clock *DriveStartTime `json:"clock,omitempty"`
	OffenseTimeouts int32 `json:"offense_timeouts,omitempty"`
	DefenseTimeouts int32 `json:"defense_timeouts,omitempty"`
	YardLine int32 `json:"yard_line,omitempty"`
	YardsToGoal int32 `json:"yards_to_goal,omitempty"`
	Down int32 `json:"down,omitempty"`
	Distance int32 `json:"distance,omitempty"`
	YardsGained int32 `json:"yards_gained,omitempty"`
	Scoring bool `json:"scoring,omitempty"`
	PlayType string `json:"play_type,omitempty"`
	PlayText string `json:"play_text,omitempty"`
	Ppa float64 `json:"ppa,omitempty"`
	Wallclock string `json:"wallclock,omitempty"`
}
