/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LivePlayByPlayPlays struct {
	Id int32 `json:"id,omitempty"`
	HomeScore int32 `json:"homeScore,omitempty"`
	AwayScore int32 `json:"awayScore,omitempty"`
	Period int32 `json:"period,omitempty"`
	Clock string `json:"clock,omitempty"`
	Wallclock string `json:"wallclock,omitempty"`
	TeamId int32 `json:"teamId,omitempty"`
	Team *interface{} `json:"team,omitempty"`
	Down int32 `json:"down,omitempty"`
	Distance int32 `json:"distance,omitempty"`
	YardsToGoal int32 `json:"yardsToGoal,omitempty"`
	YardsGained int32 `json:"yardsGained,omitempty"`
	PlayTypeId int32 `json:"playTypeId,omitempty"`
	PlayType string `json:"playType,omitempty"`
	Epa float64 `json:"epa,omitempty"`
	GarbageTime bool `json:"garbageTime,omitempty"`
	Success bool `json:"success,omitempty"`
	RushPass string `json:"rushPass,omitempty"`
	DownType string `json:"downType,omitempty"`
	PlayText string `json:"playText,omitempty"`
}
