/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GameWeather struct {
	Id int32 `json:"id,omitempty"`
	Season int32 `json:"season,omitempty"`
	Week int32 `json:"week,omitempty"`
	SeasonType string `json:"seasonType,omitempty"`
	StartTime string `json:"startTime,omitempty"`
	GameIndoors bool `json:"gameIndoors,omitempty"`
	HomeTeam string `json:"homeTeam,omitempty"`
	HomeConference string `json:"homeConference,omitempty"`
	AwayTeam string `json:"awayTeam,omitempty"`
	AwayConference string `json:"awayConference,omitempty"`
	VenueId int32 `json:"venueId,omitempty"`
	Venue string `json:"venue,omitempty"`
	Temperature float64 `json:"temperature,omitempty"`
	DewPoint float64 `json:"dewPoint,omitempty"`
	Humidity float64 `json:"humidity,omitempty"`
	Precipitation float64 `json:"precipitation,omitempty"`
	Snowfall float64 `json:"snowfall,omitempty"`
	WindDirection float64 `json:"windDirection,omitempty"`
	WindSpeed float64 `json:"windSpeed,omitempty"`
	Pressure float64 `json:"pressure,omitempty"`
	WeatherConditionCode int32 `json:"weatherConditionCode,omitempty"`
	WeatherCondition string `json:"weatherCondition,omitempty"`
}
