/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AdvancedSeasonStatOffenseRushingPlays struct {
	Rate float64 `json:"rate,omitempty"`
	Ppa float64 `json:"ppa,omitempty"`
	TotalPPA float64 `json:"totalPPA,omitempty"`
	SuccessRate float64 `json:"successRate,omitempty"`
	Explosiveness float64 `json:"explosiveness,omitempty"`
}
