/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ScoreboardGame struct {
	Id int32 `json:"id,omitempty"`
	StartDate string `json:"startDate,omitempty"`
	StartTimeTBD bool `json:"startTimeTBD,omitempty"`
	Tv string `json:"tv,omitempty"`
	NeutralSite bool `json:"neutralSite,omitempty"`
	ConferenceGame bool `json:"conferenceGame,omitempty"`
	Status string `json:"status,omitempty"`
	Period int32 `json:"period,omitempty"`
	Clock string `json:"clock,omitempty"`
	Situation string `json:"situation,omitempty"`
	Possession string `json:"possession,omitempty"`
	Venue *ScoreboardGameVenue `json:"venue,omitempty"`
	HomeTeam *ScoreboardGameHomeTeam `json:"homeTeam,omitempty"`
	AwayTeam *ScoreboardGameHomeTeam `json:"awayTeam,omitempty"`
	Weather *ScoreboardGameWeather `json:"weather,omitempty"`
	Betting *ScoreboardGameBetting `json:"betting,omitempty"`
}
