/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GameLines struct {
	Id int32 `json:"id,omitempty"`
	Season int32 `json:"season,omitempty"`
	Week int32 `json:"week,omitempty"`
	SeasonType string `json:"seasonType,omitempty"`
	StartDate string `json:"startDate,omitempty"`
	HomeTeam string `json:"homeTeam,omitempty"`
	HomeConference string `json:"homeConference,omitempty"`
	HomeScore int32 `json:"homeScore,omitempty"`
	AwayTeam string `json:"awayTeam,omitempty"`
	AwayConference string `json:"awayConference,omitempty"`
	AwayScore int32 `json:"awayScore,omitempty"`
	Lines []GameLinesLines `json:"lines,omitempty"`
}
