/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LivePlayByPlayTeams struct {
	TeamId int32 `json:"teamId,omitempty"`
	Team string `json:"team,omitempty"`
	HomeAway string `json:"homeAway,omitempty"`
	Points int32 `json:"points,omitempty"`
	Drives int32 `json:"drives,omitempty"`
	ScoringOpportunities int32 `json:"scoringOpportunities,omitempty"`
	PointsPerOpportunity float64 `json:"pointsPerOpportunity,omitempty"`
	Plays int32 `json:"plays,omitempty"`
	LineYards int32 `json:"lineYards,omitempty"`
	LineYardsPerRush float64 `json:"lineYardsPerRush,omitempty"`
	SecondLevelYards int32 `json:"secondLevelYards,omitempty"`
	SecondLevelYardsPerRush float64 `json:"secondLevelYardsPerRush,omitempty"`
	OpenFieldYards int32 `json:"openFieldYards,omitempty"`
	OpenFieldYardsPerRush float64 `json:"openFieldYardsPerRush,omitempty"`
	EpaPerPlay float64 `json:"epaPerPlay,omitempty"`
	TotalEpa float64 `json:"totalEpa,omitempty"`
	PassingEpa float64 `json:"passingEpa,omitempty"`
	EpaPerPass float64 `json:"epaPerPass,omitempty"`
	RushingEpa float64 `json:"rushingEpa,omitempty"`
	EpaPerRush float64 `json:"epaPerRush,omitempty"`
	SuccessRate float64 `json:"successRate,omitempty"`
	StandardDownSuccessRate float64 `json:"standardDownSuccessRate,omitempty"`
	PassingDownSuccessRate float64 `json:"passingDownSuccessRate,omitempty"`
	Explosiveness float64 `json:"explosiveness,omitempty"`
}
