/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TeamMatchup struct {
	Team1 string `json:"team1,omitempty"`
	Team2 string `json:"team2,omitempty"`
	StartYear int32 `json:"startYear,omitempty"`
	EndYear int32 `json:"endYear,omitempty"`
	Team1Wins int32 `json:"team1Wins,omitempty"`
	Team2Wins int32 `json:"team2Wins,omitempty"`
	Ties int32 `json:"ties,omitempty"`
	Games []TeamMatchupGames `json:"games,omitempty"`
}
