/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ReturningProduction struct {
	Season int32 `json:"season,omitempty"`
	Team string `json:"team,omitempty"`
	Conference string `json:"conference,omitempty"`
	TotalPPA float64 `json:"totalPPA,omitempty"`
	TotalPassingPPA float64 `json:"totalPassingPPA,omitempty"`
	TotalReceivingPPA float64 `json:"totalReceivingPPA,omitempty"`
	TotalRushingPPA float64 `json:"totalRushingPPA,omitempty"`
	PercentPPA float64 `json:"percentPPA,omitempty"`
	PercentPassingPPA float64 `json:"percentPassingPPA,omitempty"`
	PercentReceivingPPA float64 `json:"percentReceivingPPA,omitempty"`
	PercentRushingPPA float64 `json:"percentRushingPPA,omitempty"`
	Usage float64 `json:"usage,omitempty"`
	PassingUsage float64 `json:"passingUsage,omitempty"`
	ReceivingUsage float64 `json:"receivingUsage,omitempty"`
	RushingUsage float64 `json:"rushingUsage,omitempty"`
}
