/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TeamLocation struct {
	VenueId int32 `json:"venue_id,omitempty"`
	Name string `json:"name,omitempty"`
	City string `json:"city,omitempty"`
	State string `json:"state,omitempty"`
	Zip string `json:"zip,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	Timezone string `json:"timezone,omitempty"`
	Latitude float64 `json:"latitude,omitempty"`
	Longitude float64 `json:"longitude,omitempty"`
	Elevation float64 `json:"elevation,omitempty"`
	Capacity float64 `json:"capacity,omitempty"`
	YearConstructed float64 `json:"year_constructed,omitempty"`
	Grass bool `json:"grass,omitempty"`
	Dome bool `json:"dome,omitempty"`
}
