/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RankingWeek struct {
	Season int32 `json:"season,omitempty"`
	SeasonType string `json:"seasonType,omitempty"`
	Week int32 `json:"week,omitempty"`
	Polls []RankingWeekPolls `json:"polls,omitempty"`
}
