/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConferenceSpRating struct {
	Year int32 `json:"year,omitempty"`
	Conference string `json:"conference,omitempty"`
	Rating float64 `json:"rating,omitempty"`
	SecondOrderWins float64 `json:"secondOrderWins,omitempty"`
	Sos float64 `json:"sos,omitempty"`
	Offense *ConferenceSpRatingOffense `json:"offense,omitempty"`
	Defense *ConferenceSpRatingDefense `json:"defense,omitempty"`
	SpecialTeams *TeamSpRatingSpecialTeams `json:"specialTeams,omitempty"`
}
