/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TeamRecord struct {
	Year int32 `json:"year,omitempty"`
	Team string `json:"team,omitempty"`
	Conference string `json:"conference,omitempty"`
	Division string `json:"division,omitempty"`
	ExpectedWins float64 `json:"expectedWins,omitempty"`
	Total *TeamRecordTotal `json:"total,omitempty"`
	ConferenceGames *TeamRecordTotal `json:"conferenceGames,omitempty"`
	HomeGames *TeamRecordTotal `json:"homeGames,omitempty"`
	AwayGames *TeamRecordTotal `json:"awayGames,omitempty"`
}
