/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GameMedia struct {
	Id int32 `json:"id,omitempty"`
	Season int32 `json:"season,omitempty"`
	Week int32 `json:"week,omitempty"`
	SeasonType string `json:"seasonType,omitempty"`
	StartTime string `json:"startTime,omitempty"`
	IsStartTimeTBD bool `json:"isStartTimeTBD,omitempty"`
	HomeTeam string `json:"homeTeam,omitempty"`
	HomeConference string `json:"homeConference,omitempty"`
	AwayTeam string `json:"awayTeam,omitempty"`
	AwayConference string `json:"awayConference,omitempty"`
	MediaType string `json:"mediaType,omitempty"`
	Outlet string `json:"outlet,omitempty"`
}
