/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Recruit struct {
	Id int32 `json:"id,omitempty"`
	AthleteId int32 `json:"athleteId,omitempty"`
	RecruitType string `json:"recruitType,omitempty"`
	Year int32 `json:"year,omitempty"`
	Ranking int32 `json:"ranking,omitempty"`
	Name string `json:"name,omitempty"`
	School string `json:"school,omitempty"`
	CommittedTo string `json:"committedTo,omitempty"`
	Position string `json:"position,omitempty"`
	Height float64 `json:"height,omitempty"`
	Weight int32 `json:"weight,omitempty"`
	Stars int32 `json:"stars,omitempty"`
	Rating float64 `json:"rating,omitempty"`
	City string `json:"city,omitempty"`
	StateProvince string `json:"stateProvince,omitempty"`
	Country string `json:"country,omitempty"`
	HometownInfo *RecruitHometownInfo `json:"hometownInfo,omitempty"`
}
