/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GameLinesLines struct {
	Provider string `json:"provider,omitempty"`
	Spread float64 `json:"spread,omitempty"`
	FormattedSpread string `json:"formattedSpread,omitempty"`
	SpreadOpen float64 `json:"spreadOpen,omitempty"`
	OverUnder float64 `json:"overUnder,omitempty"`
	OverUnderOpen float64 `json:"overUnderOpen,omitempty"`
	HomeMoneyline float64 `json:"homeMoneyline,omitempty"`
	AwayMoneyline float64 `json:"awayMoneyline,omitempty"`
}
