/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TeamSeason struct {
	School string `json:"school,omitempty"`
	Year string `json:"year,omitempty"`
	Games int32 `json:"games,omitempty"`
	Wins int32 `json:"wins,omitempty"`
	Losses int32 `json:"losses,omitempty"`
	Ties int32 `json:"ties,omitempty"`
	// Rank in the AP preseason poll
	PreseasonRank int32 `json:"preseason_rank,omitempty"`
	// Final ranking in the AP poll
	PostseasonRank int32 `json:"postseason_rank,omitempty"`
	// Final SRS rankings
	Srs float64 `json:"srs,omitempty"`
	// Final overall SP+ rating
	SpOverall float64 `json:"sp_overall,omitempty"`
	// Final SP+ offensive rating
	SpOffense float64 `json:"sp_offense,omitempty"`
	// Final SP+ defensive rating
	SpDefense float64 `json:"sp_defense,omitempty"`
}
