/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.8
 * Contact: admin@collegefootballdata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AdvancedSeasonStatOffense struct {
	Plays int32 `json:"plays,omitempty"`
	Drives int32 `json:"drives,omitempty"`
	Ppa float64 `json:"ppa,omitempty"`
	TotalPPA float64 `json:"totalPPA,omitempty"`
	SuccessRate float64 `json:"successRate,omitempty"`
	Explosiveness float64 `json:"explosiveness,omitempty"`
	PowerSuccess float64 `json:"powerSuccess,omitempty"`
	StuffRate float64 `json:"stuffRate,omitempty"`
	LineYards float64 `json:"lineYards,omitempty"`
	LineYardsTotal float64 `json:"lineYardsTotal,omitempty"`
	SecondLevelYards float64 `json:"secondLevelYards,omitempty"`
	SecondLevelYardsTotal int32 `json:"secondLevelYardsTotal,omitempty"`
	OpenFieldYards float64 `json:"openFieldYards,omitempty"`
	OpenFieldYardsTotal int32 `json:"openFieldYardsTotal,omitempty"`
	TotalOpportunies int32 `json:"totalOpportunies,omitempty"`
	PointsPerOpportunity float64 `json:"pointsPerOpportunity,omitempty"`
	FieldPosition *AdvancedSeasonStatOffenseFieldPosition `json:"fieldPosition,omitempty"`
	Havoc *TeamSpRatingDefenseHavoc `json:"havoc,omitempty"`
	StandardDowns *AdvancedSeasonStatOffenseStandardDowns `json:"standardDowns,omitempty"`
	PassingDowns *AdvancedSeasonStatOffenseStandardDowns `json:"passingDowns,omitempty"`
	RushingPlays *AdvancedSeasonStatOffenseRushingPlays `json:"rushingPlays,omitempty"`
	PassingPlays *AdvancedSeasonStatOffenseRushingPlays `json:"passingPlays,omitempty"`
}
